version: '3.0'
services:

  # POSTGRES
  postgres-dev:
    container_name: vic_agr_dev
    image: postgres:12
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - vic-local

  postgres-test:
    container_name: vic_agr_test
    image: postgres:12
    env_file:
      - .test.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5434:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - vic-local

  # REDIS
  redis:
    image: redis:6.0
    ports:
      - '6378:6379'

  # Elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    env_file:
      - .development.env
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  pgdata:
  esdata:

networks:
  vic-local:

